In [11]:
import pandas as pd
from pathlib import Path
import numpy as np

In [3]:
raw_data_path = Path.cwd().parent / "data" / "raw" / "aapl.parquet"

df = pd.read_parquet(raw_data_path)
df.head()

        date symbol       open       high        low      close     volume
0 2020-01-02   AAPL  71.409785  72.460784  71.156682  72.400520  135480400
1 2020-01-03   AAPL  71.629153  72.455966  71.472469  71.696648  146322800
2 2020-01-06   AAPL  70.819208  72.306506  70.568510  72.267937  118387200
3 2020-01-07   AAPL  72.277594  72.533110  71.708710  71.928070  108872000
4 2020-01-08   AAPL  71.631552  73.386423  71.631552  73.085106  132079200

In [ ]:
df['month'] = df['date'].dt.month
df['day'] = df['date'].dt.day

In [ ]:
def compute_ma(df: pd.DataFrame, window: int=20) -> pd.DataFrame:
    df['ma' + str(window)] = df['close'].rolling(window=window).mean()
    return df
df = compute_ma(df)
df.iloc[-20:]

,date,symbol,open,high,low,close,volume,ma20
1575,2026-04-10,AAPL,259.980011,262.190002,259.019989,260.480011,31291500,253.285000
1576,2026-04-13,AAPL,259.730011,260.179993,256.660004,259.200012,36234700,253.739001
1577,2026-04-14,AAPL,259.250000,261.929993,257.190002,258.829987,48370700,254.039500
1578,2026-04-15,AAPL,258.160004,266.559998,257.809998,266.429993,49913500,254.649500
1579,2026-04-16,AAPL,266.799988,267.160004,261.269989,263.399994,43323100,255.322499
1580,2026-04-17,AAPL,266.959991,272.299988,266.720001,270.230011,61436200,256.385999
1581,2026-04-20,AAPL,270.329987,274.279999,270.290009,273.049988,36590200,257.638998
1582,2026-04-21,AAPL,271.500000,272.799988,265.399994,266.170013,50209800,258.372999
1583,2026-04-22,AAPL,267.820007,273.739990,266.869995,273.170013,43249200,259.449500
1584,2026-04-23,AAPL,275.049988,275.769989,271.649994,273.429993,33399600,260.489999
1585,2026-04-24,AAPL,272.760010,273.059998,269.649994,271.059998,38157100,261.398499
1586,2026-04-27,AAPL,266.089996,268.359985,265.070007,267.609985,41466800,262.338998
1587,2026-04-28,AAPL,272.339996,273.230011,268.660004,270.709991,40018900,263.542998
1588,2026-04-29,AAPL,267.549988,271.040009,267.040009,270.170013,30047900,264.361999
1589,2026-04-30,AAPL,270.500000,276.000000,268.140015,271.350006,91848200,265.147999
1590,2026-05-01,AAPL,278.859985,287.220001,278.369995,280.140015,79915400,266.359000
1591,2026-05-04,AAPL,279.660004,280.630005,274.859985,276.829987,46668400,267.257500
1592,2026-05-05,AAPL,276.929993,284.570007,276.500000,284.179993,49311700,268.791499
1593,2026-05-06,AAPL,281.920013,288.029999,281.070007,287.510010,58336100,270.222000
1594,2026-05-07,AAPL,289.269989,292.130005,285.779999,287.440002,45145500,271.569501

In [10]:
def compute_rsi(df: pd.DataFrame, window=14) -> pd.DataFrame:
    delta = df['close'].diff()
    gain = (delta.where(delta > 0, 0)).rolling(window=window).mean()
    loss = (-delta.where(delta < 0, 0)).rolling(window=window).mean()
    rs = gain / loss
    rsi = 100 - (100 / (1 + rs))
    df['rsi' + str(window)] = rsi
    return df

df = compute_rsi(df)
df.iloc[-20:]

,date,symbol,open,high,low,close,volume,ma20,rsi,rsi14
1575,2026-04-10,AAPL,259.980011,262.190002,259.019989,260.480011,31291500,253.285000,67.468576,67.468576
1576,2026-04-13,AAPL,259.730011,260.179993,256.660004,259.200012,36234700,253.739001,61.497203,61.497203
1577,2026-04-14,AAPL,259.250000,261.929993,257.190002,258.829987,48370700,254.039500,60.651847,60.651847
1578,2026-04-15,AAPL,258.160004,266.559998,257.809998,266.429993,49913500,254.649500,67.104297,67.104297
1579,2026-04-16,AAPL,266.799988,267.160004,261.269989,263.399994,43323100,255.322499,62.184100,62.184100
1580,2026-04-17,AAPL,266.959991,272.299988,266.720001,270.230011,61436200,256.385999,73.359513,73.359513
1581,2026-04-20,AAPL,270.329987,274.279999,270.290009,273.049988,36590200,257.638998,78.396396,78.396396
1582,2026-04-21,AAPL,271.500000,272.799988,265.399994,266.170013,50209800,258.372999,63.386716,63.386716
1583,2026-04-22,AAPL,267.820007,273.739990,266.869995,273.170013,43249200,259.449500,67.062287,67.062287
1584,2026-04-23,AAPL,275.049988,275.769989,271.649994,273.429993,33399600,260.489999,67.043043,67.043043
1585,2026-04-24,AAPL,272.760010,273.059998,269.649994,271.059998,38157100,261.398499,62.007903,62.007903
1586,2026-04-27,AAPL,266.089996,268.359985,265.070007,267.609985,41466800,262.338998,64.430353,64.430353
1587,2026-04-28,AAPL,272.339996,273.230011,268.660004,270.709991,40018900,263.542998,62.674400,62.674400
1588,2026-04-29,AAPL,267.549988,271.040009,267.040009,270.170013,30047900,264.361999,60.628057,60.628057
1589,2026-04-30,AAPL,270.500000,276.000000,268.140015,271.350006,91848200,265.147999,61.635629,61.635629
1590,2026-05-01,AAPL,278.859985,287.220001,278.369995,280.140015,79915400,266.359000,69.310230,69.310230
1591,2026-05-04,AAPL,279.660004,280.630005,274.859985,276.829987,46668400,267.257500,65.745284,65.745284
1592,2026-05-05,AAPL,276.929993,284.570007,276.500000,284.179993,49311700,268.791499,65.594806,65.594806
1593,2026-05-06,AAPL,281.920013,288.029999,281.070007,287.510010,58336100,270.222000,71.071508,71.071508
1594,2026-05-07,AAPL,289.269989,292.130005,285.779999,287.440002,45145500,271.569501,67.056489,67.056489

In [ ]:
def compute_atr(df: pd.DataFrame) -> pd.DataFrame:
    # compute ATR
    high_low = df['high'] - df['low']
    high_close = abs(df['high'] - df['close'].shift())
    low_close = abs(df['low'] - df['close'].shift())
    true_range = pd.DataFrame({'high_low': high_low, 'high_close': high_close, 'low_close': low_close}).max(axis=1)
    df['ATR'] = true_range.rolling(window=14).mean()
    return df
df = compute_atr(df)
df.iloc[-20:]

,date,symbol,open,high,low,close,volume,ma20,rsi,rsi14,ATR
1575,2026-04-10,AAPL,259.980011,262.190002,259.019989,260.480011,31291500,253.285000,67.468576,67.468576,6.096427
1576,2026-04-13,AAPL,259.730011,260.179993,256.660004,259.200012,36234700,253.739001,61.497203,61.497203,5.897142
1577,2026-04-14,AAPL,259.250000,261.929993,257.190002,258.829987,48370700,254.039500,60.651847,60.651847,5.858570
1578,2026-04-15,AAPL,258.160004,266.559998,257.809998,266.429993,49913500,254.649500,67.104297,67.104297,6.240713
1579,2026-04-16,AAPL,266.799988,267.160004,261.269989,263.399994,43323100,255.322499,62.184100,62.184100,6.216428
1580,2026-04-17,AAPL,266.959991,272.299988,266.720001,270.230011,61436200,256.385999,73.359513,73.359513,6.322142
1581,2026-04-20,AAPL,270.329987,274.279999,270.290009,273.049988,36590200,257.638998,78.396396,78.396396,6.228570
1582,2026-04-21,AAPL,271.500000,272.799988,265.399994,266.170013,50209800,258.372999,63.386716,63.386716,6.142856
1583,2026-04-22,AAPL,267.820007,273.739990,266.869995,273.170013,43249200,259.449500,67.062287,67.062287,6.479998
1584,2026-04-23,AAPL,275.049988,275.769989,271.649994,273.429993,33399600,260.489999,67.043043,67.043043,6.382854
1585,2026-04-24,AAPL,272.760010,273.059998,269.649994,271.059998,38157100,261.398499,62.007903,62.007903,6.207139
1586,2026-04-27,AAPL,266.089996,268.359985,265.070007,267.609985,41466800,262.338998,64.430353,64.430353,5.694996
1587,2026-04-28,AAPL,272.339996,273.230011,268.660004,270.709991,40018900,263.542998,62.674400,62.674400,5.649998
1588,2026-04-29,AAPL,267.549988,271.040009,267.040009,270.170013,30047900,264.361999,60.628057,60.628057,5.574999
1589,2026-04-30,AAPL,270.500000,276.000000,268.140015,271.350006,91848200,265.147999,61.635629,61.635629,5.909997
1590,2026-05-01,AAPL,278.859985,287.220001,278.369995,280.140015,79915400,266.359000,69.310230,69.310230,6.770711
1591,2026-05-04,AAPL,279.660004,280.630005,274.859985,276.829987,46668400,267.257500,65.745284,65.745284,6.844284
1592,2026-05-05,AAPL,276.929993,284.570007,276.500000,284.179993,49311700,268.791499,65.594806,65.594806,6.795713
1593,2026-05-06,AAPL,281.920013,288.029999,281.070007,287.510010,58336100,270.222000,71.071508,71.071508,6.872140
1594,2026-05-07,AAPL,289.269989,292.130005,285.779999,287.440002,45145500,271.569501,67.056489,67.056489,6.689998

In [ ]:
def compute_pipeline(df: pd.DataFrame) -> pd.DataFrame:
    df = compute_ma(df)
    df = compute_rsi(df)
    df = compute_atr(df)
    df = df.dropna()
    return df